main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security_login:
    path: /connexion
    defaults: { _controller: FOSUserBundle:Security:login }
    requirements:
        methods: GET|POST